language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "node"
before_script:
  - export CHROME_BIN=chromium-browser
  - npm install -g grunt-cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  - TEST_DIR=project/xtypejs
  - TEST_DIR=project/extensions/xtypejs-extension-custom-types
script: cd $TEST_DIR && npm install && npm test