language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "node"
  - "iojs"
before_script:
  - export CHROME_BIN=chromium-browser
  - npm install -g grunt-cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start